name: Deploy with Hugo

on:
  push:
    branches:
      - source # 或者你想触发的分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo_version: '0.148.1'
        extended: true
    - name: Build Site
      run: hugo
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.HUGO_BLOG }}
        publish_dir: ./public
        publish_branch: main
